server:
  port: 8081
spring:
  application:
    name: long-tx-service
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    org:
      springframework:
        web: DEBUG