server:
  port: 8080

spring:
  application:
    name: client-app
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-Url: http://localhost:9411
logging:
#  pattern:
#    level: %d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n
  level:
    org:
      springframework:
        web: DEBUG